name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build_linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: laytan/setup-odin@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release: false
      - uses: mymindstorm/setup-emsdk@v14
      - uses: actions/checkout@v4
      - name: Set Script Permissions
        run: chmod +x build.bat
      - name: Build debug
        run: bash build.bat debug
      - name: Build release
        run: bash build.bat release
      - name: Build web
        run: bash build.bat web
      - name: Upload web build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

  build_macos:
    name: MacOS
    strategy:
      matrix:
        os: [macos-13, macos-15]
    runs-on: ${{matrix.os}}
    steps:
      - uses: laytan/setup-odin@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release: false
      - uses: mymindstorm/setup-emsdk@v14
      - uses: actions/checkout@v4
      - name: Set Script Permissions
        run: chmod +x build.bat
      - name: Build debug
        run: bash build.bat debug
      - name: Build release
        run: bash build.bat release
      - name: Build web
        run: bash build.bat web

  build_windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: laytan/setup-odin@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release: false
      - uses: mymindstorm/setup-emsdk@v14
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build debug
        run: ./build.bat debug
      - name: Build release
        run: ./build.bat release
      - name: Build web
        run: ./build.bat web

  deploy:
    name: Deploy GitHub Pages
    needs: build_linux
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
